-- User profile fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS photo_url VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS oab_number VARCHAR;
