-- Migration 001: Baseline schema (snapshot as of 2026-03-06)
-- This is the initial schema documentation. All tables already exist in production.
-- This migration is idempotent (CREATE TABLE IF NOT EXISTS).

CREATE TABLE IF NOT EXISTS conversations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  phone VARCHAR(30) NOT NULL,
  role ENUM('user','assistant') NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  from_bot TINYINT(1) DEFAULT 1,
  KEY idx_phone (phone),
  KEY idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS leads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  phone VARCHAR(30) NOT NULL UNIQUE,
  name VARCHAR(255) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  visa_type VARCHAR(100) DEFAULT NULL,
  status ENUM('new','qualified','contacted','scheduled') DEFAULT 'new',
  transfer_to_human TINYINT(1) DEFAULT 0,
  first_contact TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_interaction TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  lead_score INT DEFAULT 0,
  lead_status ENUM('cold','warm','qualified','hot') DEFAULT 'cold',
  current_status VARCHAR(100) DEFAULT NULL,
  profession VARCHAR(255) DEFAULT NULL,
  timeline VARCHAR(100) DEFAULT NULL,
  urgency ENUM('normal','alta','critica') DEFAULT 'normal',
  escalated TINYINT(1) DEFAULT 0,
  consultation_scheduled TINYINT(1) DEFAULT 0,
  notes TEXT DEFAULT NULL,
  source VARCHAR(100) DEFAULT 'whatsapp',
  message_count INT DEFAULT 0,
  conversation_state VARCHAR(50) DEFAULT NULL,
  is_urgent TINYINT(1) DEFAULT 0,
  client_name VARCHAR(255) DEFAULT NULL,
  user_phone VARCHAR(30) DEFAULT NULL,
  visa_interest VARCHAR(255) DEFAULT NULL,
  whatsapp_name VARCHAR(255) DEFAULT NULL,
  language VARCHAR(5) DEFAULT 'en',
  moskit_sent TINYINT(1) DEFAULT 0,
  moskit_id INT DEFAULT NULL,
  auto_registered TINYINT(1) DEFAULT 0,
  consultation_type ENUM('free','paid') DEFAULT NULL,
  consultation_datetime DATETIME DEFAULT NULL,
  stripe_session_id VARCHAR(255) DEFAULT NULL,
  payment_status ENUM('pending','paid','failed','refunded') DEFAULT NULL,
  payment_amount INT DEFAULT NULL,
  payment_currency VARCHAR(10) DEFAULT NULL,
  calendly_event_uri VARCHAR(500) DEFAULT NULL,
  source_platform VARCHAR(20) DEFAULT 'whatsapp',
  gclid VARCHAR(255) DEFAULT NULL,
  fbclid VARCHAR(255) DEFAULT NULL,
  utm_source VARCHAR(100) DEFAULT NULL,
  utm_campaign VARCHAR(100) DEFAULT NULL,
  utm_medium VARCHAR(100) DEFAULT NULL,
  messenger_id VARCHAR(100) DEFAULT NULL,
  whatsapp_from_messenger TINYINT(1) DEFAULT 0,
  followup_count INT DEFAULT 0,
  last_followup_at DATETIME DEFAULT NULL,
  registered_in_moskit TINYINT(1) DEFAULT 0,
  awaiting_consultation_followup INT DEFAULT 0,
  last_consultation_followup_at DATETIME DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  intake_form_state ENUM('not_started','invited','in_progress','completed','expired','skipped') DEFAULT 'not_started',
  intake_form_current_question INT DEFAULT 0,
  intake_form_started_at DATETIME DEFAULT NULL,
  intake_form_completed_at DATETIME DEFAULT NULL,
  intake_form_final_score INT DEFAULT 0,
  intake_form_primary_pathway VARCHAR(50) DEFAULT NULL,
  intake_form_gemini_summary TEXT DEFAULT NULL,
  eligible_for_free_call TINYINT(1) DEFAULT 0,
  intake_form_invite_sent_at DATETIME DEFAULT NULL,
  intake_form_followup_count INT DEFAULT 0,
  intake_form_last_followup_at DATETIME DEFAULT NULL,
  bot_enabled TINYINT(1) DEFAULT 1,
  last_read_at TIMESTAMP NULL DEFAULT NULL,
  human_takeover TINYINT(1) DEFAULT 0,
  needs_human_review TINYINT(1) DEFAULT 0,
  human_review_reason VARCHAR(255) DEFAULT NULL,
  quick_intake_answers LONGTEXT DEFAULT NULL,
  quick_intake_scoring LONGTEXT DEFAULT NULL,
  quick_intake_completed TINYINT(1) DEFAULT 0,
  needs_auto_followup TINYINT(1) DEFAULT 0,
  auto_followup_requested_at DATETIME DEFAULT NULL,
  auto_followup_completed_at DATETIME DEFAULT NULL,
  auto_followup_message TEXT DEFAULT NULL,
  never_contact TINYINT(1) DEFAULT 0,
  never_contact_reason VARCHAR(255) DEFAULT NULL,
  contact_type ENUM('lead','active_client','past_client','partner','other','blocked') DEFAULT 'lead',
  contact_tags VARCHAR(255) DEFAULT NULL,
  last_notification_at DATETIME DEFAULT NULL,
  last_notification_reason VARCHAR(255) DEFAULT NULL,
  quick_intake_declined TINYINT(1) DEFAULT 0,
  quick_intake_declined_at DATETIME DEFAULT NULL,
  legal_advice_blocked_count INT DEFAULT 0,
  last_legal_advice_block TIMESTAMP NULL DEFAULT NULL,
  KEY idx_status (status),
  KEY idx_needs_human_review (needs_human_review),
  KEY idx_legal_advice_blocked (legal_advice_blocked_count)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS intake_questions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  question_id INT NOT NULL UNIQUE,
  question_pt TEXT NOT NULL,
  question_en TEXT NOT NULL,
  question_es TEXT NOT NULL,
  response_type ENUM('text','boolean','choice','date','file') DEFAULT 'text',
  category VARCHAR(50) NOT NULL,
  max_points INT DEFAULT 0,
  pathway_impact VARCHAR(50) DEFAULT NULL,
  skip_if_question_id INT DEFAULT NULL,
  skip_if_answer VARCHAR(50) DEFAULT NULL,
  options_pt TEXT DEFAULT NULL,
  options_en TEXT DEFAULT NULL,
  options_es TEXT DEFAULT NULL,
  is_active TINYINT(1) DEFAULT 1,
  display_order INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS intake_form_responses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  phone VARCHAR(30) NOT NULL,
  question_id INT NOT NULL,
  question_text TEXT DEFAULT NULL,
  response_text TEXT DEFAULT NULL,
  response_type ENUM('text','boolean','choice','date','skip','file') DEFAULT 'text',
  question_category VARCHAR(50) DEFAULT NULL,
  points_earned INT DEFAULT 0,
  gemini_analysis TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_phone (phone),
  KEY idx_question_id (question_id),
  KEY idx_category (question_category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS messenger_conversations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  messenger_id VARCHAR(100) NOT NULL,
  role ENUM('user','assistant') NOT NULL,
  content TEXT NOT NULL,
  conversation_state VARCHAR(50) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_messenger_id (messenger_id),
  KEY idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS messenger_leads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  messenger_id VARCHAR(100) NOT NULL UNIQUE,
  fb_name VARCHAR(255) DEFAULT NULL,
  client_name VARCHAR(255) DEFAULT NULL,
  whatsapp_number VARCHAR(30) DEFAULT NULL,
  conversation_state VARCHAR(50) DEFAULT 'msg_new',
  reengagement_sent TINYINT(1) DEFAULT 0,
  reengagement_sent_at DATETIME DEFAULT NULL,
  converted_to_whatsapp TINYINT(1) DEFAULT 0,
  converted_at DATETIME DEFAULT NULL,
  lead_phone VARCHAR(30) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_interaction TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_state (conversation_state),
  KEY idx_converted (converted_to_whatsapp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pathway_scores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  phone VARCHAR(30) NOT NULL,
  pathway ENUM('family_based','employment_based','humanitarian_asylum','humanitarian_vawa','humanitarian_u_visa','humanitarian_t_visa','humanitarian_sijs','investor','unknown') NOT NULL,
  score INT DEFAULT 0,
  confidence DECIMAL(3,2) DEFAULT 0.00,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY idx_phone_pathway (phone, pathway)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
